baseURL = 'https://andrewflemming.net/'
languageCode = 'en-us'
title = "Andrew Flemming"
theme = "ananke"
publishDir = 'docs'
timeZone = 'America/Toronto'
Copyright = "Andrew Flemming"
pluralizeListTitles = false
paginate = 5
summaryLength = 2
enableGitInfo = true


[permalinks]
  blog = '/:section/:year/:slug/'

[outputs]
  home = [ "RSS", "HTML"]
  section  = ["HTML"]
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[menu]
[[menu.main]]
  identifier = 'projects'
  name = 'Projects'
  title = 'projects'
  url = '/projects/'
  weight = 1
#[[menu.main]]
#  identifier = 'career'
#  name = 'Career'
#  title = 'career'
#  url = '/career/'
#  weight = 2
[[menu.main]]
  identifier = 'photography'
  name = 'Photos'
  url = '/photography/'
  weight = 3
[[menu.main]]
  identifier = 'videos'
  name = 'Videos'
  title = 'videos'
  url = '/videos/'
  weight = 4
[[menu.main]]
  identifier = 'blog'
  name = 'Blog'
  title = 'blog'
  url = '/blog/'
  weight = 5

[params]
  read_more_copy = "⚓︎"
  author = "Andrew Flemming"
  favicon = "/images/favicon.png"
  site_logo = ""
  description = "Hi 👋"
  facebook = ""
  twitter = "https://twitter.com/aflemm"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/andrew-flemming-aab98731/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = "http://andrewflemming.net/feed.xml"
  tiktok = ""
  
  mainSections = ["blog"]

  allPostsURL = "/blog/archive"
  allPostsText = "Full Archive"

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  body_classes = "avenir bg-white"
  post_content_classes = "f5 f4-l lh-copy nested-copy-line-height nested-links"

  featured_image = "/images/header-summer.jpg"
  cover_dimming_class = "bg-black-10"
  
  recent_posts_number = 2
  
  env = "production"

[frontmatter]
	date = ["date", "publishDate", "lastmod"]
	lastmod = ["lastmod", ":git", "date", "publishDate"]
	publishDate = ["publishDate", "date"]
	expiryDate = ["expiryDate"]