baseURL = 'https://andrewflemming.net/'
languageCode = 'en-us'
title = "Andrew"
theme = "ananke"
publishDir = 'docs'
Copyright = "Andrew Flemming"
sectionPagesMenu = ['photography', 'projects', 'career', 'blog']
pluralizeListTitles = false

[menu]
[[menu.main]]
  identifier = 'projects'
  name = 'Projects'
  title = 'projects'
  url = '/projects/'
  weight = 1
[[menu.main]]
  identifier = 'photography'
  name = 'Photography'
  title = 'photography'
  url = '/photography/'
  weight = 2
#[[menu.main]]
#  identifier = 'career'
#  name = 'Career'
#  title = 'career'
#  url = '/career/'
#  weight = 3
[[menu.main]]
  identifier = 'blog'
  name = 'Blog'
  title = 'blog'
  url = '/blog/'
  weight = 4

[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "Hi 👋"
  facebook = ""
  twitter = "https://twitter.com/aflemm"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  tiktok = ""

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  body_classes = "avenir bg-white"
  post_content_classes = "avenir bg-white"

  featured_image = "/images/header-summer.jpg"
  cover_dimming_class = "bg-black-10"
  
  recent_posts_number = 2
